adb uninstall com.nebula.mamu 
adb uninstall com.forshared 
adb uninstall com.miniclip.eightballpool 
adb uninstall com.taxis99 
adb uninstall in.AajTak.headlines 
adb uninstall com.brokendiamond.advance.car.parking.car.driver.simulator 
adb uninstall com.alibaba.aliexpresshd 
adb uninstall all.video.downloader.allvideodownloader 
adb uninstall mix.any.downloader.video.all.anyvideodownloader.hd.musicaly 
adb uninstall com.domobile.applock 
adb uninstall com.bcp.bank.bcp 
adb uninstall com.banesco.banescomovil.tcmbve.android 
adb uninstall com.commsource.beautyplus 
adb uninstall com.fss.unbipsp 
adb uninstall sg.bigo.live 
adb uninstall com.monstergamesproductions.ramp.moto.rider 
adb uninstall com.timuzgames.bikeracing2018 
adb uninstall com.billiards.city.pool.nation.club 
adb uninstall com.differencetenderwhite.skirt 
adb uninstall im.thebot.messenger 
adb uninstall com.mastercarryheat.straw 
adb uninstall ng.jiji.app 
adb uninstall com.appstar.callrecorder 
adb uninstall io.teslatech.callbreak 
adb uninstall com.king.candycrushsaga 
adb uninstall com.careem.acma 
adb uninstall com.solou.catendless.run 
adb uninstall com.jetstartgames.chess 
adb uninstall com.nazara.chhotabheemeggdrive 
adb uninstall com.city.coach.bus.simulator.drive 
adb uninstall com.cleanmaster.mguard 
adb uninstall club.fromfactory 
adb uninstall com.ksmobile.launcher 
adb uninstall com.fatcat.CookingPastaInTheKitchen 
adb uninstall com.cricbuzz.android 
adb uninstall com.xprodev.cutcam 
adb uninstall com.th.ringtone.maker 
adb uninstall com.games2win.drivingacademyindia 
adb uninstall com.dbdev.dailynewshunt 
adb uninstall ir.divar 
adb uninstall com.greenteagames.dogracing3d 
adb uninstall com.ansangha.drdriving 
adb uninstall com.firsttouchgames.dls3 
adb uninstall com.duapps.recorder 
adb uninstall com.ludashi.dualspace 
adb uninstall com.google.android.apps.tachyon 
adb uninstall com.eboks.activities 
adb uninstall pk.com.telenor.phoenix 
adb uninstall com.escape.room.door.word.prison.puzzle.adventure 
adb uninstall com.aim.racing 
adb uninstall com.eyecon.global 
adb uninstall com.farming.tractor.realharvest.simulator 
adb uninstall com.fast.vpnfree 
adb uninstall com.google.android.apps.nbu.files 
adb uninstall com.puzzles.game.halloweeen.one 
adb uninstall com.NikSanTech.FireDots3D 
adb uninstall eu.livesport.FlashScore_com 
adb uninstall com.revolverolver.fliptrickster 
adb uninstall com.flipkart.android 
adb uninstall za.co.fnb.connect.itt 
adb uninstall com.fordeal.android 
adb uninstall com.dts.freefireth 
adb uninstall com.ketchapp.fruitmaster 
adb uninstall com.sky.funnyfruitsplash 
adb uninstall co.go.fynd 
adb uninstall com.gaana 
adb uninstall com.wla.live.earthview.maps.pro.gpsfinder.apps 
adb uninstall com.grabtaxi.passenger 
adb uninstall com.yy.hiyo 
adb uninstall com.game5mobile.lineandwater 
adb uninstall hd.video.player.hd.videoplayer 
adb uninstall com.h8games.helixjump 
adb uninstall com.physics.sim.game.cat 
adb uninstall com.imhelo 
adb uninstall com.ehawk.proxy.freevpn 
adb uninstall com.bestfreegames.busracinghillclimb 
adb uninstall com.fingersoft.hillclimb 
adb uninstall in.startv.hotstar 
adb uninstall iflix.play 
adb uninstall com.imo.android.imoimbeta 
adb uninstall com.imo.android.imous 
adb uninstall com.imo.android.imoim 
adb uninstall cris.org.in.prs.ima 
adb uninstall com.motaso.itvtanzania 
adb uninstall com.abscbn.iwantNow 
adb uninstall com.jabong.android 
adb uninstall com.techlogix.mobilinkcustomer 
adb uninstall com.jio.media.jiobeats 
adb uninstall com.jollycorp.jollychic 
adb uninstall com.tencent.ibg.joox 
adb uninstall com.sc.jumia 
adb uninstall com.direxplay.ecard 
adb uninstall com.khmercreator.khmermusicbox 
adb uninstall appwallet.com.kidsphotoeditor 
adb uninstall com.lazada.android 
adb uninstall video.like 
adb uninstall com.shopping.limeroad 
adb uninstall jp.naver.line.android 
adb uninstall com.facebook.lite 
adb uninstall com.mobiusx.live4dresults 
adb uninstall com.livescore 
adb uninstall com.moonfrog.ludo.club 
adb uninstall com.ludo.king 
adb uninstall com.hippogames.ludosaga 
adb uninstall com.opex.makemyvideostatus 
adb uninstall com.oneapp.max.cleaner.booster 
adb uninstall com.oneapp.max.security.pro 
adb uninstall com.mcdonalds.app 
adb uninstall com.synergygb.mercantil.banco.bancamovil 
adb uninstall com.facebook.mlite 
adb uninstall tdp.app.col 
adb uninstall com.bitel.selfcare 
adb uninstall com.appsomniacs.da2 
adb uninstall com.timuzgames.missioncounterattack 
adb uninstall africa.finserve.mkey 
adb uninstall com.mobile.truecall.tracker.locator.teccreations 
adb uninstall com.mobile.legends 
adb uninstall photoable.findlocation.onnumb.montage.llc 
adb uninstall dk.danskebank.mobilepay 
adb uninstall com.mobstar 
adb uninstall com.tbegames.and.best_moto_race 
adb uninstall com.mxtech.videoplayer.ad 
adb uninstall com.myairtelapp 
adb uninstall com.outfit7.mytalkingangelafree 
adb uninstall com.outfit7.mytalkingtom2 
adb uninstall com.outfit7.mytalkingtomfree 
adb uninstall com.telenor.pakistan.mytelenor 
adb uninstall com.portonics.mygp 
adb uninstall com.jio.myjio 
adb uninstall com.mtn1app 
adb uninstall com.myntra.android 
adb uninstall com.selfcare.safaricom 
adb uninstall com.telkomsel.telkomselcm 
adb uninstall dk.e_nettet.mobilekey.everyone 
adb uninstall com.fosllevbv 
adb uninstall com.whatdir.stickers 
adb uninstall com.fsn.nykaa 
adb uninstall ru.ok.android 
adb uninstall com.opera.app.news 
adb uninstall com.percent.mybest 
adb uninstall com.sofeh.android.musicstudio3 
adb uninstall com.microsoft.office.outlook 
adb uninstall com.oyo.consumer 
adb uninstall io.voodoo.paper2 
adb uninstall com.lbe.parallel.intl 
adb uninstall com.superking.parchisi.star 
adb uninstall com.dstukalov.walocalstoragestickers 
adb uninstall com.hefe.pro.editor 
adb uninstall com.roidapp.photogrid 
adb uninstall com.zentertain.videoflip 
adb uninstall com.bizsolution.keyboard 
adb uninstall com.picsart.studio 
adb uninstall com.plato.android 
adb uninstall com.mizo.police.airplane.transporter 
adb uninstall com.mizo.police.robot.transformation2 
adb uninstall me.pou.app 
adb uninstall com.antivirus.speed.cleaner 
adb uninstall com.psiphon3.subscription 
adb uninstall com.tencent.ig 
adb uninstall com.gamma.scan 
adb uninstall com.ffgames.racingincar2 
adb uninstall com.gbs.HighwayTraffic.racingin.car.e.speedracer.htcr.turbo 
adb uninstall com.tbegames.and.best_monster_racing 
adb uninstall com.droidhen.game.racingmoto 
adb uninstall com.gravity.ro.and 
adb uninstall com.rahazachumbani.app 
adb uninstall freehdev.proj.hamzap.videoplayer 
adb uninstall ridmik.keyboard 
adb uninstall com.riseup.game 
adb uninstall com.rocket.cleaner.app 
adb uninstall com.roposo.android 
adb uninstall com.netease.chiji 
adb uninstall org.hicham.salaat 
adb uninstall com.rocket.tools.clean.antivirus.master 
adb uninstall in.mohalla.sharechat 
adb uninstall com.zzkko 
adb uninstall com.shopclues 
adb uninstall com.shopee.ph 
adb uninstall com.silverdialer.app 
adb uninstall com.zenjoy.slideshow 
adb uninstall cab.snapp.passenger.play 
adb uninstall com.Sniper3D.Gun.Shooter.Free.Shooting.Games3D 
adb uninstall com.fungames.sniper3d 
adb uninstall com.heavy.excavator.simulator.driveandtransport 
adb uninstall app.sooper 
adb uninstall com.soundcloud.android 
adb uninstall com.hyperspeed.rocketclean.pro 
adb uninstall com.custom.spillit 
adb uninstall com.spotify.music 
adb uninstall com.downlood.sav.whmedia 
adb uninstall com.lazygeniouz.saveit 
adb uninstall com.mindy.grap1 
adb uninstall com.gamelead.street.archer.run 
adb uninstall com.combineinc.streetracing.driftthreeD 
adb uninstall com.steelcloudstudio.stunt.bike.racing.game.tricks.master 
adb uninstall com.kiloo.subwaysurf 
adb uninstall com.cam001.selfie 
adb uninstall com.ufotosoft.justshot 
adb uninstall com.swingman.game 
adb uninstall com.outfit7.talkingtom 
adb uninstall ee.mtakso.client 
adb uninstall com.teenpatti.hd.gold 
adb uninstall com.octro.teenpatti 
adb uninstall com.imangi.templerun2 
adb uninstall com.imangi.templerun 
adb uninstall com.testfoni.android 
adb uninstall com.spilgames.ThrillRush1 
adb uninstall com.amanotes.beathopper 
adb uninstall craftsilicon.barclays 
adb uninstall com.tunnelguru.toofan 
adb uninstall com.skgames.trafficrider 
adb uninstall com.google.android.apps.translate 
adb uninstall com.companyname.TrenchAssault 
adb uninstall trendyol.com 
adb uninstall com.truecaller 
adb uninstall us.remotecontrol.TVRemote.tools4tv 
adb uninstall com.youdao.hindict 
adb uninstall com.ubercab.eats 
adb uninstall com.ubercab 
adb uninstall com.UCMobile.intl 
adb uninstall com.uc.browser.en 
adb uninstall com.percent.mybest3 
adb uninstall com.asiainno.uplive 
adb uninstall com.viber.voip 
adb uninstall video.downloader.videodownloader 
adb uninstall com.funcamerastudio.videomaker 
adb uninstall com.xvideostudio.videoeditor 
adb uninstall com.vivashow.share.video.chat 
adb uninstall com.ss.android.ugc.boomlite 
adb uninstall com.cheerfulinc.flipagram 
adb uninstall com.viu.phone 
adb uninstall com.viusasa 
adb uninstall com.quvideo.xiaoying 
adb uninstall org.videolan.vlc 
adb uninstall com.uc.vmlite 
adb uninstall com.yomobigroup.chat 
adb uninstall vn.vtv.vtvgo 
adb uninstall com.waze 
adb uninstall com.tencent.mm 
adb uninstall com.redefine.welike 
adb uninstall com.whatsapp 
adb uninstall com.whereismytrain.android 
adb uninstall com.bitmango.go.wheresmyavocadodrawlines 
adb uninstall com.halo.wifikey.wifilocating 
adb uninstall com.contextlogic.wish 
adb uninstall com.word.game.fun.puzzle.prison.escape.captain 
adb uninstall cn.xender 
adb uninstall com.cyberlink.youcammakeup 
adb uninstall com.cyberlink.youperfect 
adb uninstall com.fun.share 
adb uninstall com.zaful 
adb uninstall com.zing.zalo 
adb uninstall com.dewmobile.kuaiya.play 
adb uninstall com.zayan.ui2 
adb uninstall me.zepeto.main 
adb uninstall com.application.zomato 
adb uninstall com.mobirix.zombieking 